apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
metadata:
  name: "sentry-redis"
  namespace: "demo"
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: "redis-sentry"
  chart:
    repository: "https://charts.bitnami.com/bitnami"
    name: "redis"
    version: "11.1.3"
  values:
    nameOverride: "sentry-redis"
    fullnameOverride: "sentry-redis"
    usePassword: false
    cluster:
      enabled: true
    image:
      tag: 6.0.10-debian-10-r1
    master:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 512Mi
    slave:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
